# Services overrides for testing in development

services:

  app-git:
    # Extend
    extends:
      service: app
    # Build override
    image: ${IMAGES_PREFIX:-app}-test-watch-git:${IMAGES_TAG:-latest}
    build:
      target: app_test_watch_git
    # Deploy override
    depends_on: !reset null
    environment: !reset null
    tmpfs: !reset null
    volumes: !override
      - .:/ref
      - app-git:/git
    develop: !override
      watch:
        # Docker image
        - action: rebuild
          path: ./app/Dockerfile
        # Application build files
        - action: rebuild
          path: ./app/docker/test-watch-git-command.sh
        # Application source code
        - action: restart
          path: ./.git/refs/heads

  app:
    # Extend
    extends:
      file: ./docker-compose.test.yml
      service: app
    # Build override
    image: ${IMAGES_PREFIX:-app}-test-watch:${IMAGES_TAG:-latest}
    build:
      target: app_test_watch
    # Deploy override
    depends_on:
      app-git:
        condition: service_completed_successfully
        restart: false
    volumes:
      - app-git:/git
    develop:
      watch:
        # Docker image
        - action: rebuild
          path: ./app/Dockerfile
        # Application build files
        - action: rebuild
          path: ./app/app/pnpm-lock.yaml
        - action: rebuild
          path: ./app/docker/test-watch-command.sh
        # Application source code
        - action: sync
          path: ./app/app
          target: /app

volumes:

  app-git:
